name: "Octave Static Code Analysis for MATLAB"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  analyze:
    name: Analyze MATLAB Code with Octave
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Octave
      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      # Step 3: Create the MATLAB analysis script
      - name: Create MATLAB analysis script
        run: |
          echo "Your analyze-code.m content here" > .github/custom-queries/matlab/analyze-code.m

      # Step 4: Run the analysis script using Octave
      - name: Run static code analysis
        run: |
          octave --no-gui .github/custom-queries/matlab/analyze-code.m

      # Step 5: Convert results from .mat to SARIF
      - name: Convert MAT to SARIF
        run: |
          # Load the .mat file and convert it to a SARIF file
          octave --no-gui -e "
            load('code-analysis-results.mat'); 
            sarif = struct('version', '2.1.0', 'runs', []);
            for i = 1:length(results)
              fileIssues = results{i, 2}; 
              sarif.runs(end + 1) = struct('tool', struct('driver', struct('name', 'MATLAB Static Analysis', 'version', '1.0')), ...
                                            'results', struct('ruleId', 'MATLAB_Analysis', ...
                                            'message', struct('text', fileIssues), ...
                                            'locations', struct('physicalLocation', struct('artifactLocation', struct('uri', results{i, 1})))));
            end
            save('code-analysis-results.sarif', 'sarif', '-json');
          "

      # Step 6: Upload SARIF file to GitHub Security tab
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: code-analysis-results.sarif
