name: "Octave Static Code Execution for MATLAB"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  analyze:
    name: Analyze MATLAB Code with Octave
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Octave
      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      # Step 3: Run all MATLAB files and log errors
      - name: Run all .m files
        run: |
          mkdir -p output
          for file in $(find . -name "*.m"); do
            octave --no-gui $file >> output/octave_output.log 2>&1 || {
              echo "Error executing $file. Check output/octave_output.log for details."
              exit 1
            }
          done

      # Step 4: Upload results
      - name: Upload output logs
        uses: actions/upload-artifact@v3
        with:
          name: octave-output
          path: output/octave_output.log
