name: Octave Static Code Analysis

on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Octave
      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      # Step 3: Install Python and required packages
      - name: Install Python
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install sarif-om

      # Step 4: Run the static code analysis using Octave
      - name: Run Octave analysis
        run: |
          export DISPLAY=""
          cd .github/custom-queries/matlab # Change to the directory containing the script
          octave --no-gui analyze_code.m

      # Step 5: Convert JSON to SARIF
      - name: Convert JSON to SARIF
        run: |
          python3 -c "
          import json
          import sarif_om as sarif

          with open('code-analysis-results.json') as f:
              issues = json.load(f)

          runs = [sarif.Run(
              tool=sarif.Tool(name='Octave Analysis'), 
              results=[
                  sarif.Result(
                      ruleId=issue[1][i]['ruleId'], 
                      message=sarif.Message(text=issue[1][i]['message']), 
                      locations=[sarif.Location(
                          physicalLocation=sarif.PhysicalLocation(
                              artifactLocation=sarif.ArtifactLocation(uri=issue[0])
                          )
                      )]
                  ) for i in range(len(issue[1])) 
              ]
          ) for issue in issues]

          sarif_log = sarif.SarifLog(schemaVersion='2.1.0', runs=runs)
          with open('code-analysis-results.sarif', 'w') as sarif_file:
              sarif_file.write(sarif_log.json(exclude_none=True))
          "

      # Step 6: Upload the SARIF results
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: code-analysis-results.sarif
