name: "Custom CodeQL Analysis for MATLAB Security"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  analyze:
    name: Analyze MATLAB Code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        language: 'javascript'  # Generic language selection
        

    - name: Autobuild project
      run: echo "No build step needed for MATLAB"

    - name: Create CodeQL Database
      run: |
        codeql database create matlab-db --language=javascript --source-root=.

    - name: Run Custom CodeQL Queries
      run: |
        codeql query run --database=matlab-db custom-queries/matlab/*.ql

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
