name: "Octave Static Code Analysis for MATLAB"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  analyze:
    name: Analyze MATLAB Code with Octave
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Octave
      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      # Step 3: Check for .m files in the repository
      - name: Find .m files
        id: find_files
        run: |
          m_files=$(find . -name "*.m")
          if [ -z "$m_files" ]; then
            echo "No .m files found!"
            exit 1
          else
            echo "$m_files"
          fi

      # Step 4: Create MATLAB analysis script in the correct location
      - name: Create MATLAB analysis script
        run: |
          echo "% Add current directory and subdirectories to path" > analyze_code.m
          echo "addpath(genpath(pwd));" >> analyze_code.m
          echo "% Find all .m files" >> analyze_code.m
          echo "files = dir('**/*.m');" >> analyze_code.m
          echo "% Initialize analysis results" >> analyze_code.m
          echo "results = {};" >> analyze_code.m
          echo "% Analyze each file" >> analyze_code.m
          echo "for k = 1:length(files)" >> analyze_code.m
          echo "  filePath = fullfile(files(k).folder, files(k).name);" >> analyze_code.m
          echo "  fid = fopen(filePath, 'r');" >> analyze_code.m
          echo "  code = fread(fid, '*char')';" >> analyze_code.m
          echo "  fclose(fid);" >> analyze_code.m
          echo "  % Add any custom analysis logic here" >> analyze_code.m
          echo "  issues = {};" >> analyze_code.m
          echo "  if ~isempty(issues)" >> analyze_code.m
          echo "    results{end+1} = {filePath, issues};" >> analyze_code.m
          echo "  end" >> analyze_code.m
          echo "end" >> analyze_code.m
          echo "% Save the analysis results to a .mat file" >> analyze_code.m
          echo "save('code-analysis-results.mat', 'results');" >> analyze_code.m

      # Step 5: Run the static code analysis using Octave
      - name: Run MATLAB code analysis with Octave
        run: |
          octave --no-gui analyze_code.m

      # Verify the .mat file was created successfully
      - name: Confirm .mat file creation
        run: |
          if [ ! -f code-analysis-results.mat ]; then
            echo "Analysis results (.mat file) were not generated."
            exit 1
          fi

      # Step 6: Display .mat file results
      - name: Display analysis results
        run: |
          echo "% Load and display .mat file contents" > display_results.m
          echo "load('code-analysis-results.mat');" >> display_results.m
          echo "disp('Analysis Results:');" >> display_results.m
          echo "disp(results);" >> display_results.m
          octave --no-gui display_results.m
